import chalk from 'chalk'
import {
  BOAR,
  CAPTAIN,
  CURSED,
  DRAGON,
  EAGLE,
  HERO,
  HORSE,
  MAGE,
  SNAKE,
  SOLDIER,
  TRAITOR,
  WOLF,
} from './constants.js'
import type { SymbolType } from './types.js'
import { display, solve } from './utils.js'

// biome-ignore format: preserve array formatting for readability
const CHALLENGES: SymbolType[][] = [
  [HERO, HERO, HERO, CAPTAIN, SOLDIER, SOLDIER, SOLDIER],
  [HERO, HERO, CAPTAIN, CAPTAIN, CAPTAIN, CAPTAIN, TRAITOR],
  [HERO, HERO, HERO, CAPTAIN, CAPTAIN, CAPTAIN, CURSED],
  [HERO, HERO, HERO, HERO, SOLDIER, TRAITOR, CURSED],
  [SOLDIER, SOLDIER, SOLDIER, SOLDIER, SOLDIER, SOLDIER, MAGE],
  [HERO, HERO, CAPTAIN, SOLDIER, SOLDIER, SOLDIER, MAGE],
  [HERO, HERO, CAPTAIN, SOLDIER, SOLDIER, CURSED, MAGE],
  [HERO, CAPTAIN, CAPTAIN, CAPTAIN, CURSED, CURSED, MAGE],
  [HERO, HERO, CAPTAIN, CAPTAIN, SOLDIER, TRAITOR, MAGE],
  [HERO, HERO, CAPTAIN, TRAITOR, TRAITOR, TRAITOR, MAGE],
  [HERO, HERO, CAPTAIN, CAPTAIN, TRAITOR, CURSED, MAGE],
  [HERO, HERO, SOLDIER, SOLDIER, TRAITOR, MAGE, MAGE],
  [SOLDIER, CURSED, CURSED, MAGE, MAGE, MAGE, MAGE],
  [HERO, CAPTAIN, CAPTAIN, CURSED, MAGE, MAGE, MAGE],
  [HERO, SOLDIER, TRAITOR, TRAITOR, MAGE, MAGE, MAGE],
  [HERO, HERO, HERO, CAPTAIN, SOLDIER, SOLDIER, MAGE, WOLF],
  [HERO, CAPTAIN, CAPTAIN, CAPTAIN, SOLDIER, TRAITOR, MAGE, WOLF],
  [HERO, SOLDIER, SOLDIER, SOLDIER, TRAITOR, MAGE, MAGE, WOLF],
  [HERO, SOLDIER, SOLDIER, CURSED, CURSED, CURSED, MAGE, SNAKE],
  [HERO, TRAITOR, TRAITOR, CURSED, MAGE, MAGE, MAGE, SNAKE],
  [HERO, HERO, CAPTAIN, TRAITOR, CURSED, MAGE, MAGE, SNAKE],
  [HERO, CAPTAIN, CAPTAIN, CAPTAIN, SOLDIER, SOLDIER, MAGE, HORSE],
  [HERO, HERO, CAPTAIN, CAPTAIN, SOLDIER, TRAITOR, MAGE, HORSE],
  [HERO, CAPTAIN, TRAITOR, CURSED, MAGE, MAGE, MAGE, HORSE],
  [SOLDIER, SOLDIER, SOLDIER, CURSED, CURSED, CURSED, MAGE, DRAGON],
  [HERO, HERO, HERO, HERO, TRAITOR, CURSED, MAGE, DRAGON],
  [HERO, HERO, CAPTAIN, SOLDIER, TRAITOR, MAGE, MAGE, DRAGON],
  [CAPTAIN, CAPTAIN, CAPTAIN, SOLDIER, CURSED, CURSED, MAGE, BOAR],
  [HERO, HERO, TRAITOR, CURSED, CURSED, MAGE, MAGE, BOAR],
  [HERO, TRAITOR, TRAITOR, CURSED, MAGE, MAGE, MAGE, BOAR],
  [HERO, HERO, CAPTAIN, SOLDIER, CURSED, CURSED, MAGE, EAGLE],
  [HERO, HERO, CAPTAIN, SOLDIER, SOLDIER, TRAITOR, MAGE, EAGLE],
  [HERO, HERO, HERO, SOLDIER, TRAITOR, MAGE, MAGE, EAGLE],
  [HERO, HERO, SOLDIER, SOLDIER, TRAITOR, MAGE, MAGE, HORSE, BOAR],
  [SOLDIER, SOLDIER, CURSED, CURSED, CURSED, MAGE, MAGE, WOLF, DRAGON],
  [HERO, SOLDIER, SOLDIER, TRAITOR, MAGE, MAGE, MAGE, HORSE, EAGLE],
  [HERO, SOLDIER, SOLDIER, TRAITOR, TRAITOR, MAGE, MAGE, DRAGON, BOAR],
  [HERO, HERO, SOLDIER, TRAITOR, TRAITOR, TRAITOR, MAGE, SNAKE, EAGLE],
  [HERO, CAPTAIN, CAPTAIN, TRAITOR, MAGE, MAGE, MAGE, WOLF, HORSE],
  [HERO, SOLDIER, SOLDIER, SOLDIER, CURSED, CURSED, MAGE, SNAKE, DRAGON],
  [HERO, HERO, SOLDIER, SOLDIER, TRAITOR, MAGE, MAGE, WOLF, EAGLE],
  [HERO, HERO, HERO, TRAITOR, TRAITOR, CURSED, MAGE, DRAGON, BOAR],
  [HERO, HERO, TRAITOR, CURSED, CURSED, MAGE, MAGE, WOLF, BOAR],
  [SOLDIER, SOLDIER, SOLDIER, SOLDIER, SOLDIER, CAPTAIN, MAGE, WOLF, SNAKE],
  [CAPTAIN, SOLDIER, SOLDIER, SOLDIER, MAGE, MAGE, MAGE, HORSE, EAGLE],
  [HERO, HERO, CAPTAIN, SOLDIER, TRAITOR, CURSED, MAGE, WOLF, WOLF],
  [HERO, SOLDIER, SOLDIER, TRAITOR, TRAITOR, TRAITOR, MAGE, SNAKE, BOAR],
  [HERO, HERO, TRAITOR, TRAITOR, TRAITOR, CURSED, MAGE, WOLF, EAGLE],
  [HERO, HERO, CAPTAIN, CAPTAIN, CAPTAIN, TRAITOR, MAGE, WOLF, SNAKE],
  [HERO, HERO, CAPTAIN, TRAITOR, MAGE, MAGE, MAGE, SNAKE, HORSE],
]

CHALLENGES.forEach((symbols, index) => {
  const key = chalk.bold.underline(`Challenge #${index + 1}`)

  console.time(key)
  const [armyA, armyB] = solve([...symbols])
  console.timeEnd(key)

  const solution = `${display(armyA, true)} === ${display(armyB, true)}`

  console.log(chalk.bold('Draft: ') + display(symbols, false, false))
  console.log(chalk.bold('Solution: ') + chalk.grey(solution))
  console.log('')
})
